import { User, Company, MealRecord, UserRole, MealType } from '../types';

const STORAGE_KEYS = {
  USERS: 'idealcontrol_users',
  COMPANIES: 'idealcontrol_companies',
  MEALS: 'idealcontrol_meals',
  SESSION: 'idealcontrol_session'
};

const EMPLOYEES_LIST = [
  "ABIGAIL BADE", "ADEILDO ARAUJO GOMES", "ADELINO JUNIOR SILVA", "ADELMAR DOS SANTOS MOURA JUNIOR",
  "ADONIAS NUNES FOLHA", "ADRIANO COSTA PEREIRA", "ADRIANO DA ROCHA", "ADRIANO SALVADOR SANTANA DA SILVA",
  "AFONSO VIEIRA DA SILVA", "AGNALDO LEAL DE CASTRO", "AILTON PEREIRA RODRIGUES", "AIRTON MARQUES ROCHA",
  "ALDECY PEREIRA DA SILVA", "ALEX SANTANA BARBOSA", "ALEXANDRE SOARES DOS SANTOS", "ALEXSANDRO DE SOUSA FERREIRA",
  "ALFREDO DA ROCHA", "ALFREDO GUILHERME SOARES DE ANOLASCO", "ANDERSON ALVES SOARES", "ANDERSON SANTANA DA SILVA",
  "ANDRE FERNANDES DE SOUSA OLIVEIRA", "ANDRE LUIZ MIRANDA CARVALHO", "ANDRE PINHEIRO PESSOA", "ANDRESSA DE SOUSA VIDAL",
  "ANDREY TACIO SANTOS DO LAGO", "ANTONIEL SANTOS CAPISTANO", "ANTONIO DA SILVA BRANCO", "ANTONIO GOMES DE SOUSA",
  "ANTONIO MARCOS PEREIRA DE SOUZA", "ANTONIO WILTON MOTA", "ARNALDO ENGERLHARD ZIMPEL NETO", "ATAGILDO DOMINGOS FERREIRA",
  "ATAIDE ALEXANDRE DA SILVA", "ATEVAL SABOIA DOS SANTOS", "BRUNO FERREIRA ARAUJO", "CAIO MAYCON DA COSTA FERREIRA",
  "CAMILA VERONICA DE SOUZA", "CARLOS ANTONIO LEITE RIBEIRO", "CARLOS DANIEL DE SOUSA CARDOSO", "CARLOS DANIEL PEREIRA DA SILVA",
  "CARLOS HENRIQUE COSTA DE MORAIS", "CARLOS MARQUES GUEDES", "CLAUDINEI FERREIRA", "CLAUDIO DE SOUSA SANTANA",
  "CLEBISSON IVO DE CARVALHO JUNIOR", "CLEITON DE SOUSA FIALHO", "CLESIO DOS PASSOS GUIMARAES", "CRISNA LAIANE CARVALHO LOPES",
  "CRISTIANE MAMEDIO PINHEIRO", "DANIEL ARAUJO FERREIRA", "DEBORA DE LIMA DOS SANTOS", "DENILSON DE JESUS SANTOS",
  "DENILSON DOS SANTOS CARVALHO", "DENILSON LIMA DA SILVA", "DERIVALDO SILVA LIMA", "DIEGO SENA FERREIRA",
  "DIOGENES FRANCO", "DIOGO RIBEIRO DA SILVA", "EBNER JULIANO DA SILVA ROBIM", "EDGAR OLIVEIRA DOS SANTOS",
  "EDIMARCOS GUILHERME DE OLIVEIRA", "EDINALDO LEAL DE SOUSA", "EDMILSON MONTEIRO DE ARAUJO", "EDSON BRAUNA DOS SANTOS",
  "EDUARDO VENTURIN MORAIS", "EDUARDO XAVIER PEREIRA DA SILVA", "ELAINE LEITE DE QUEIROS", "ELDINEY GOMES BARROS",
  "ELESSANDRO ANTUNES DE JESUS", "ELIVELTON FERREIRA DUARTE", "ELOIZA ANTUNES DE JESUS", "EMERSON DA SILVA OLIVEIRA",
  "EMERSON DA SILVA SANTOS", "ERIK FRAZIO BARBOSA DA SILVA", "EVALDO DE MACEDO FALCAO JUNIOR", "EVANILSON DA SILVA CAMPOS",
  "EVERSON HENRIQUE DAMAS MACIEL", "EZEQUIEL SILVA PONCE", "FABIO DA SILVA RAMOS", "FERNANDO SANTANA DA SILVA",
  "FERNANDO SELLA", "FRANCIDALVA DOS SANTOS", "FRANCISCA DE PAULA SILVA NETA", "FRANCISCO RENATO NUNES DA SILVA",
  "GARDIEL BARROS FEITOSA", "GEAN LEITE DOS SANTOS", "GELSON FEITOSA DA SILVA", "GENILSON PAZ DA SILVA",
  "GENIVALDO DUARTE FERREIRA", "GEORGE OLIVEIRA FEITOSA", "GEOVANE DA SILVA COSTA", "GERSON GOMES DO NASCIMENTO",
  "GESAILDO FERREIRA RODRIGUES", "GILBERTO GOMES BARBOSA", "GILDEAN ALMEIDA PEREIRA", "GILMAR FRANCISCO DE SOUSA FILHO",
  "GILSON VIANA MARTINS", "GISELI VIVIANE GARCIA CLAUDINO", "GRACIANO DE SOUSA", "GUILBERTH LUIGI NASCIMENTO CHAVES",
  "GUILHERME NERES DE ARAUJO", "GUSTAVO DA SILVA BARBOSA", "GUSTAVO LEAL CARVALHO", "GUTEMBERGH DOS SANTOS CARVALHO",
  "HEBERT FONSECA GUERRA", "HELIO SOUSA PEREIRA", "HIGOR RODRIGUES BARBOSA", "HIPOLITO CHAPLA",
  "HOZANAN LEMES DA SILVA SANTOS", "IDCLOUD NV", "ISAAC SANTANA LEAL", "ISMAEL DA SILVA SANTOS", "ITALO OLIVEIRA RODRIGUES",
  "IVAN BENEDITO DA SILVA", "JAIANE DE LIRA CARVALHO", "JAILSON LOPES ALVES", "JALDEMAR SOARES DE MATOS",
  "JARLON BRUNO BRITO SOUZA", "JEAN DA SILVA MOURA", "JEFERSSON MOURA SANTOS", "JEFFERSON DOUGLAS MIRANDA SILVA",
  "JEOVAM PONCIANO DE MORAES", "JESSE DA SILVA PEREIRA", "JHONNY FRANCISCO DE BRITO", "JOACILDO RODRIGUES DE SOUZA",
  "JOALDO DA SILVA FEITOSA", "JOAO CARLOS ROCHA DOS ANJOS", "JOAO IVAN FEITOSA DE BARROS", "JOAO MARCOS SOARES DOS SANTOS",
  "JOAO PAULO DIAS DE SOUSA", "JOAO VICTOR DE SOUSA FERREIRA", "JOAO VITOR CAGLIONE DA SILVA", "JOELSON MOURA DA SILVA",
  "JOSE ALBERICO SARAIVA JUNIOR", "JOSE AUGUSTO MARTINS DA SILVA", "JOSE CARLOS VALERIANO", "JOSE CICERO DA SILVA",
  "JOSE FRANCISCO NUNES", "JOSE GERALDO DE CARVALHO", "JOSE RONALDO DA SILVA", "JOSE VENIL SOARES SAMPAIO",
  "JOSE WILLIAM ABADE DO LAGO", "JOSELIA LOPES DA SILVA", "JOSINEY DO CARMO BASTOS", "JOVERCINO JOAQUIM DA SILVA",
  "JOYCE ELLEN LOPES SIRQUEIRA", "JUAREZ SANTANA FEITOSA", "JULIA SILVA OLIVEIRA", "JULIANO JOSE DA SILVA",
  "KAILANE OLIVEIRA DE ALMEIDA", "KAIO RUAN SANTOS DA SILVA", "KAUA MICUANSK FAGOTTE", "KAYKY LIMA PEREIRA",
  "KLEBER LEAL MIRANDA", "LAURIANE CONCEICAO DE BRITO", "LAURO CHAVES DE BRITO", "LEANDRO CONCEICAO SILVA",
  "LEANDRO NUNES RIBEIRO", "LECIO IVO DOS ANJOS", "LEONARDO PEREIRA CARDOSO DA SILVA", "LEONDAS AURELIANO DE SOUZA",
  "LETYCIA NOGUEIRA DE MENEZES", "LIDIANE DOS SANTOS PRUDENCIO MEDEIROS", "LIVAN JEFFERSON DA SILVA", "LOIANE BATISTA DOS SANTOS",
  "LUCAS CARVALHO SILVA", "LUCAS SOARES DA SILVA", "LUCIANA PEREIRA NUNES", "LUCIANO LIMA DOS SANTOS",
  "LUCIANO SILVA SOARES", "LUCIANO VIEIRA GATO", "LUCIMAR SOUZA MEDEIRO", "LUCIVALDO DOS SANTOS SOUZA",
  "LUIS FELIPE MOURA PINHEIRO", "LUIS JOSE DE MACEDO", "LUIZ FELIPE DA SILVA BARBOSA", "LUIZ ONORIO DA ROSA BRUM",
  "MADSON PEREIRA DA COSTA", "MAERVETON LOPES PEREIRA", "MARCELO RODRIGUES CAMILO", "MARCOS ANTONIO DA SILVA",
  "MARCOS AURELIO DIAS", "MARCOS DE SOUSA LISBOA", "MARCOS GONÇALVES DE ALMEIDA JUNIOR", "MARCOS JOSE DE MORAES",
  "MARIA ALCENI DE MOURA E SILVA", "MARIA CLEIDE DA ROCHA SILVA", "MARIA DE FATIMA FERREIRA ARAUJO", "MARIA LUIZA ABADE ARRUDA",
  "MARIA ONERA PACHECO MAGALHAES", "MARIA VITORIA GUARINO DE SOUZA", "MARIANE ARAUJO DE ALMEIDA", "MATEUS DA SILVA PEQUENO",
  "MAURICIO EULOGIO GRISS", "MAXUEL SOUSA SILVA", "MAYCON PEREIRA ROCHA", "MINELVINA GUARINO DOS SANTOS", "MITIEL LUCCA",
  "NAELSON DE CASTRO SOUSA", "NATYARA FELIX DOS SANTOS", "NELSON DE LARA", "NICOLAU JOSE DE OLIVEIRA",
  "NILZETE APARECIDA FERREIRA SILVA", "NONATO DA CRUZ SOARES", "ODINIL EMIDIO DA COSTA", "OLMIRO PEREIRA PITALUGA",
  "OTAVIANO CEOLATTO PIVETTA", "PAULO ARAUJO DE CARVALHO", "PAULO BAKAIRI PEDRO BORGES", "PAULO HENRIQUE DE CARVALHO MOURAO",
  "PAULO IRAN CARDOSO DA SILVA", "PAULO JOSE SANTANA DOS SANTOS", "PEDRO HENRIQUE PAIVA DA SILVA", "PEDRO HENRIQUE TORRES DAMASCENO",
  "RAFAEL DA COSTA DE MATOS", "RAFAEL KLOCK", "RAFAEL NERIS DA SILVA", "RAFAEL RODRIGUES DE SOUZA", "RAILSON TEIXEIRA ROCHA",
  "RAIMUNDO NONATO MENDES DA SILVA", "RAIMUNDO NONATO MOURA GUARINO", "RAIMUNDO NONATO NUNES DE OLIVEIRA",
  "RAIMUNDO NONATO QUINTO DE OLIVEIRA", "RAONE BRITO SOUSA", "RAUANDERSON ALVES HONORIO", "RAYFLAN OLIVEIRA RAMOS",
  "RAYLTON LEITE PEREIRA", "REGILENE BENTO BARBOSA", "RENAN ARAUJO NUNES", "RENAN SOUSA DOS SANTOS",
  "RENATO DE JESUS DOS SANTOS", "RENIVALDO DE JESUS SANTOS", "ROBERTO MAILLO DE SOUSA SILVA", "ROBSON CASSIO DOS SANTOS FARIAS",
  "RODRIGO SILVA BRITO", "ROMARIO SANTANA BARBOSA", "ROMARIO SANTOS DA SILVA", "ROMULO DIAS DE SOUSA", "RONY PAULO GUARINO",
  "ROSANA MARIA VIEIRA", "ROSILEIDE DA CONCEICAO SANTOS", "ROSIVALDO DE SOUSA", "RUAN DE SOUSA ALVES",
  "RUDIARD MOREIRA BARBOSA", "RYAN DOS SANTOS OLIVEIRA", "SALATIEL DE AQUINO FOLHA", "SALVADOR SANTANA BARBOSA",
  "SALVADOR SANTOS FELIPE", "SAMUEL RIBEIRO MATIAS", "SANTIAGO SENA FERREIRA", "SEBASTIAO GUARINO DOS SANTOS",
  "SIDINEI FERNANDES DE SOUSA", "SIDLEI SOUSA DE JESUS", "SIDNEY SOUZA DA SILVA", "SILAS MIQUEIAS NUNES PEREIRA",
  "SONNY ANDERSON DIAS DOS SANTOS", "SORAIA BORGES DIAS", "SUZANE MENDES ARAUJO", "THAIS VITORIA DAMASCENO FERREIRA SANTOS",
  "THIAGO DIAS DE MELO FRANCO", "THIAGO LIMA DE SOUSA", "THIAGO PEREIRA DUARTE", "THIAGO REZENDE VILHALBA",
  "TIAGO ANTONIO DA SILVA CIVIDINI", "TIAGO FERNANDO DE SA", "VAGNER SANTANA DE OLIVEIRA", "VALBER SILVA ALVES",
  "VALMIR PEDROSO LOURENCO NUNES", "VANDERLEI ALVES DE AMORIM", "VANDERLEY GAMA", "VANDERLY OLIVEIRA FEITOSA",
  "VANIO SANTOS DE OLIVEIRA", "VICTOR FERNANDES DA SILVA", "VICTOR OLIVEIRA DA SILVA", "WAGNER DE SOUSA SILVA",
  "WANDERLEY OLIVEIRA FEITOSA", "WANDERSON SANTANA DE OLIVEIRA", "WELISSON RODRIGUES DE SOUSA", "WENDEL FERNANDES DE OLIVEIRA",
  "WENNAS MIRANDA NUNES", "WESLEY ABADE FEITOSA", "WEYLLON VICTOR RODRIGUES CARVALHO", "WILLIAM CIRQUEIRA ARAUJO",
  "WILLIAM DOUGLAS DA SILVA", "WILLIAN BRITO PESSOA", "WILLIAN TRINDADE RODRIGUES", "GISELLA ALMEIDA SOUZA",
  "JOSÉ FRANCISCO DE OLIVEIRA NETO", "ROSENICA PATRICIA DIAS DA SILVA", "MIRIAM MARQUES MENDONÇA VILHALBA",
  "GELSON GOTTEMS IABLONSKI", "WELINTON MARCOS IABLONSKI GOMES", "JEFERSON ALEXANDRE FONSECA", "ROGERIO MENGEL",
  "MAIKE SOUZA COSTA", "MAILDON DA SILVA SANTOS", "LUCAS GUEDES DA SILVA", "LUCAS FELIPE CANDELORIO CARNEIRO",
  "HENRIQUE FELIPE MAGALHÕES", "ANTONIO ENILVALDO DOS SANTOS", "GEDER LUIZ GENZ", "LUIZ FERNANDO DOS ANJOS SILVA",
  "SERGIO RIGO GUARNIERI", "WELINGTON RODRIGO FERREIRA OLIVEIRA", "EVERTON BORGES DA SILVA", "GUSTAVO LUIS SANTOS DE ARRUDAQ",
  "ALDO JOSÉ DALLABRIDA ALMEIDA", "FABIO RODRIGO PINHEIRO DE SOUZA", "JOSÉ LUIS LINO ARAUJO"
];

// Initial Seed Data
const seedData = () => {
  // If no users exist, seed the data
  if (!localStorage.getItem(STORAGE_KEYS.USERS)) {
    const defaultCompany: Company = { id: 'comp_1', name: 'IDEAL AGRO', logoUrl: '' };
    const adminUser: User = { 
      id: 'user_1', 
      name: 'Admin', 
      companyId: 'comp_1', 
      role: UserRole.ADMIN, 
      password: 'C0ntrol' 
    };
    
    // Generate User objects for each employee name
    const employeeUsers: User[] = EMPLOYEES_LIST.map((name, index) => ({
      id: `user_emp_${index + 1000}`, // Start IDs at 1000 to avoid conflicts
      name: name,
      companyId: 'comp_1',
      role: UserRole.USER
    }));

    const allUsers = [adminUser, ...employeeUsers];
    
    localStorage.setItem(STORAGE_KEYS.COMPANIES, JSON.stringify([defaultCompany]));
    localStorage.setItem(STORAGE_KEYS.USERS, JSON.stringify(allUsers));
    localStorage.setItem(STORAGE_KEYS.MEALS, JSON.stringify([]));
  }
};

seedData();

export const StorageService = {
  // Users
  getUsers: (): User[] => {
    return JSON.parse(localStorage.getItem(STORAGE_KEYS.USERS) || '[]');
  },
  saveUser: (user: User) => {
    const users = StorageService.getUsers();
    const existingIndex = users.findIndex(u => u.id === user.id);
    if (existingIndex >= 0) {
      users[existingIndex] = user;
    } else {
      users.push(user);
    }
    localStorage.setItem(STORAGE_KEYS.USERS, JSON.stringify(users));
  },
  deleteUser: (id: string) => {
    const users = StorageService.getUsers().filter(u => u.id !== id);
    localStorage.setItem(STORAGE_KEYS.USERS, JSON.stringify(users));
  },

  // Companies
  getCompanies: (): Company[] => {
    return JSON.parse(localStorage.getItem(STORAGE_KEYS.COMPANIES) || '[]');
  },
  saveCompany: (company: Company) => {
    const companies = StorageService.getCompanies();
    const existingIndex = companies.findIndex(c => c.id === company.id);
    if (existingIndex >= 0) {
      companies[existingIndex] = company;
    } else {
      companies.push(company);
    }
    localStorage.setItem(STORAGE_KEYS.COMPANIES, JSON.stringify(companies));
  },
  deleteCompany: (id: string) => {
    const companies = StorageService.getCompanies().filter(c => c.id !== id);
    localStorage.setItem(STORAGE_KEYS.COMPANIES, JSON.stringify(companies));
  },

  // Meals
  getMeals: (): MealRecord[] => {
    return JSON.parse(localStorage.getItem(STORAGE_KEYS.MEALS) || '[]');
  },
  addMeal: (meal: MealRecord) => {
    const meals = StorageService.getMeals();
    meals.push(meal);
    localStorage.setItem(STORAGE_KEYS.MEALS, JSON.stringify(meals));
  },

  // Auth Helper
  login: (username: string, password?: string): User | null => {
    const users = StorageService.getUsers();
    // Simple insecure check for demo
    const user = users.find(u => u.name === username && (u.password === password || (!u.password && !password)));
    if (user) {
      localStorage.setItem(STORAGE_KEYS.SESSION, JSON.stringify(user));
      return user;
    }
    return null;
  },
  getCurrentUser: (): User | null => {
    const session = localStorage.getItem(STORAGE_KEYS.SESSION);
    return session ? JSON.parse(session) : null;
  },
  logout: () => {
    localStorage.removeItem(STORAGE_KEYS.SESSION);
  }
};